language: node_js
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli
- npm install
script:
- grunt
deploy:
  provider: npm
  email: npm@niteoholdings.com
  skip_cleanup: true
  api_key:
    secure: "<%= ENV['npmapikey'] %>"
  on:
    tags: true
    all_branches: true
    repo: NiteoSoftware/s3artifactor
