language: node_js
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli
- npm install
script:
- grunt
deploy:
  provider: npm
  email: npm@niteoholdings.com
  api_key:
    secure: <%= ENV['npmapikey'] %>
  on:
    tags: true
    repo: NiteoSoftware/s3artifactor
