language: node_js
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli
- npm install
script:
- grunt
deploy:
  provider: npm
  email: npm@niteoholdings.com
  skip_cleanup: true
  api_key:
    secure: "NIH1ug5gpKF3asg0pDZz4hi4Hu16joyedcQXsMyDgernj1l/pWCegRAdqenItWBTrf9SiKyk3sYxsQ55THTPDg5G29wywD1JS4GQzjl2L0AxqfAisIN2p2c67tWFuuuVWCkuMoo79UfP7J2Lr/yl2AFAWyWVJ8aVMxOaiCQzzH8="
  on:
    tags: true
    all_branches: true
    repo: NiteoSoftware/s3artifactor
